# The Docker image that will be used to build your app
image: openjdk
# Functions that should be executed before the build script is run
before_script:
  - ":"
pages:
  script:

    - javadoc -d public/doc -sourcepath src cosc202.andie cosc202.andie.ImageActions cosc202.andie.ImageOperations cosc202.andie.SelectActions
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
